on:
  workflow_call:
    inputs:
      jest_status:
        required: false
        type: string
      e2e_status:
        required: false
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Stop Docker Compose
        run: docker compose down
        if: always()

      - name: Show test results
        run: |
          echo "Jest status: ${{ inputs.jest_status }}"
          echo "E2E status: ${{ inputs.e2e_status }}"